FROM node:22-alpine

WORKDIR /app
RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml turbo.json ./
COPY apps/web/package.json ./apps/web/package.json

RUN pnpm install

COPY . .

RUN pnpm --filter web build

ENV NODE_ENV=production

EXPOSE 3000

CMD ["pnpm", "--filter", "web", "start"]
